{% set name = "pan3d" %}
{% set version = "1.1.5" %}

{% set python_min = "3.13" %}
{% set vtk_version = "9.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pan3d-{{ version }}.tar.gz
  sha256: ae1ab764ce36f2052b1e16c0057d8debf39a219601fd6c52f616e996b35ae7df

build:
  entry_points:
    - xr-viewer = pan3d.viewers.preview:main
    - xr-catalog = pan3d.viewers.catalog:main
    - xr-slicer = pan3d.explorers.slicer:main
    - xr-globe = pan3d.explorers.globe:main
    - xr-contour = pan3d.explorers.contour:main
    - xr-analytics = pan3d.explorers.analytics:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - vtk >={{ vtk_version }}
    - requests >=2.31
    - aiohttp
    - xarray >=2023.8
    # viewers/explorers
    - trame >=3.9
    - trame-vtk >=2.8.15
    - trame-vtklocal >=0.12.2
    - trame-vuetify >=3.0.1
    # esgf
    - intake-esgf >=2024.1
    # pangeo
    - intake >=2.0  # latest has plugin errors
    - intake-xarray >=2.0
    - intake-esm >=2023.11
    - s3fs >=2024.2
    - gcsfs >=2024.2
    # xcdat/analytics
    - trame-plotly
    - xcdat

test:
  imports:
    - pan3d
  commands:
    - pip check
    - xr-viewer --help
    - xr-catalog --help
    - xr-slicer --help
    - xr-globe --help
    - xr-contour --help
    - xr-analytics --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kitware/pan3d
  summary: Utility package for processing and visualizing 3D datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ayenpure
    - jourdain
